name: ci-test

on:
  push:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test.yml"
  pull_request:
    branches: [main]
    paths:
      - "KubeArmor/**"
      - "tests/**"
      - "protobuf/**"
      - ".github/workflows/ci-test.yml"

jobs:
  build:
    name: Auto-testing Framework / ${{ matrix.os }} / ${{ matrix.runtime }}
    runs-on: ${{ matrix.os }}
    env:
      RUNTIME: ${{ matrix.runtime }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        runtime: ["docker", "containerd", "crio"]
    steps:
      - name: Kernel version
        run: uname -r

      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Latest Stable LLVM toolchain
        run: |
          sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
          for tool in "clang" "llc" "llvm-strip"
          do
            sudo rm -f /usr/bin/$tool
            sudo ln -s /usr/bin/$tool-14 /usr/bin/$tool
          done
          sudo apt install libelf-dev

      - name: Setup K8s Env
        run: |
          echo "RUNTIME="$RUNTIME
          if [ "$RUNTIME" == "docker" ]; then
            ./contribution/self-managed-k8s/docker/install_docker.sh
            docker --version
          elif [ "$RUNTIME" == "crio" ]; then
            ./contribution/self-managed-k8s/crio/install_crio.sh
            crio --version
          fi
          ./contribution/k3s/install_k3s.sh

      - name: Install cmctl
        run: |
          OS=$(go env GOOS); ARCH=$(go env GOARCH); curl -sSL -o cmctl.tar.gz https://github.com/cert-manager/cert-manager/releases/download/v1.7.2/cmctl-$OS-$ARCH.tar.gz
          tar xzf cmctl.tar.gz
          sudo mv cmctl /usr/local/bin

      - name: Install annotation controller
        run: |
          kubectl apply -f deployments/annotations/cert-manager.yaml
          kubectl wait pods --for=condition=ready -n cert-manager -l app.kubernetes.io/instance=cert-manager
          cmctl check api  --wait 300s
          kubectl apply -f deployments/annotations/kubearmor-annotation-manager.yaml
          kubectl wait pods --for=condition=ready -n kube-system -l kubearmor-app=kubearmor-annotation-manager

      - name: Run kubectl proxy
        run: kubectl proxy &

      - name: Test KubeArmor
        run: ./tests/test-scenarios-github.sh
        timeout-minutes: 15

      - name: Archive log artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: kubearmor.logs
          path: |
            /tmp/kubearmor.test
            /tmp/kubearmor.log
            /tmp/kubearmor.msg

      - name: Check Results
        if: ${{ always() }}
        run: cat /tmp/kubearmor.test

      - name: Measure Code Coverage
        if: ${{ always() }}
        run: |
          go get github.com/modocache/gover
          gover    
          go tool cover -func=gover.coverprofile
        working-directory: KubeArmor
        env:
          GOPATH: /home/runner/go

      - uses: codecov/codecov-action@v2
        if: ${{ always() }}
        with:
          files: ./KubeArmor/gover.coverprofile