on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'main'

    paths:
      - 'STABLE-RELEASE'

name: KubeArmor stable release 

jobs:
  build:
    name: Create KubeArmor stable release - 18.04
    if: github.repository == 'kubearmor/kubearmor'
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2

      - name: Pull Docker Hub image
        run: |
            value=`cat STABLE-RELEASE`
            docker pull docker.io/kubearmor/kubearmor:$value
            docker image tag kubearmor/kubearmor:$value kubearmor/kubearmor:stable

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        run: ./KubeArmor/build/push_kubearmor.sh stable
